# Generated by Django 4.2.3 on 2023-07-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reddituser',
            name='display_picture',
            field=models.BooleanField(null=True),
        ),
    ]
