# Generated by Django 4.2.3 on 2023-07-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_reddituser_display_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reddituser',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
